# Generated by Django 2.2.6 on 2020-02-19 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradesperson',
            options={'verbose_name_plural': 'Tradesperson'},
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
