# Generated by Django 2.2.6 on 2020-02-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tradesperson_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesperson',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
