# Generated by Django 2.2.6 on 2020-02-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tradesperson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='image',
            field=models.ImageField(default='../Tradesperson/media/profile_image/LinkedInPic.png', upload_to='profile_image'),
        ),
    ]
