# Generated by Django 2.2.6 on 2020-02-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200229_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
