# Generated by Django 2.2.6 on 2020-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200229_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesperson',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='image',
            field=models.ImageField(blank=True, default='../Tradesperson/media/profile_image/LinkedInPic.png', null=True, upload_to='profile_image'),
        ),
    ]
