# Generated by Django 2.2.6 on 2020-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200305_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesperson',
            name='county',
            field=models.CharField(default='Dublin', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesperson',
            name='town',
            field=models.CharField(default='Smithfield', max_length=25),
            preserve_default=False,
        ),
    ]
