# Generated by Django 2.2.6 on 2020-03-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200305_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='website_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
