# Generated by Django 2.2.6 on 2020-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200308_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
