# Generated by Django 2.2.6 on 2020-03-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200308_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='working_hours',
            field=models.CharField(max_length=30),
        ),
    ]
