# Generated by Django 2.2.6 on 2020-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='My Profile'),
            preserve_default=False,
        ),
    ]
