# Generated by Django 2.2.6 on 2020-03-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg', '0003_auto_20200314_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
