# Generated by Django 2.2.6 on 2020-03-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg', '0004_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='My Profile', max_length=30),
            preserve_default=False,
        ),
    ]
