# Generated by Django 2.2.6 on 2020-03-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg', '0005_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
    ]
